name: foodie_restaurant
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.2.3+9

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.3
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2
  flutter_facebook_auth: ^6.2.0
  geoflutterfire2: ^2.3.15
  geocoding: ^3.0.0
  geolocator: ^10.0.1
  googleapis_auth: ^1.6.0
  firebase_app_check: ^0.3.0+1


  smooth_page_indicator: ^1.1.0
  image_picker: ^1.1.1
  image_gallery_saver: ^2.0.3
  flutter_easyloading: ^3.0.5
  intl: ^0.19.0
  multi_select_flutter: ^4.1.3
  cached_network_image: ^3.3.1
  intl_phone_number_input: ^0.7.4
  pin_code_fields: ^8.0.1
  easy_localization: ^3.0.7
  font_awesome_flutter: ^10.7.0
  photo_view: ^0.15.0
  flutter_native_image: ^0.0.6+1
  the_apple_sign_in: ^1.1.1
  numberpicker: ^2.1.2
  dotted_border: ^2.1.0
  datetime_picker_formfield_new: ^2.1.0
  video_player: ^2.8.6
  flutter_sound: ^9.2.13
  video_thumbnail: ^0.5.3
  video_compress: ^3.1.2
  path_provider: ^2.1.3
  sticky_headers: ^0.3.0+2
  barcode_image: ^2.0.2
  dropdown_search: ^5.0.6
  audioplayers: ^6.0.0
  esc_pos_utils: ^1.1.0
  print_bluetooth_thermal: ^1.1.0
  flutter_widget_from_html: ^0.15.0
  flutter_video_info: ^1.3.2
  mime: ^1.0.5
  flutter_rating_bar: ^4.0.1
  flutterflow_paginate_firestore: ^1.0.3+1
  flutter_multi_formatter: ^2.12.8
  mailer: ^6.1.0
  image: ^3.0.2


dependency_overrides:
  google_maps_place_picker_mb: ^3.1.2
  cloud_firestore: ^5.0.1
  uuid: ^4.4.0
  http: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/flags/
    - assets/audio/

  fonts:
    - family: Poppinsb
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppinsl
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppinsm
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppinsr
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppinssb
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf